stefan-hoeck/idris2-pack-db

.github/workflows/ci-db.yml

Can be useful for tracing/debugging builds.
Passing `-m` twice should [format the commit correctly](https://stackoverflow.com/questions/5064563/add-line-break-to-git-commit-m-from-the-command-line), but maybe would be better to use a heredoc.
Also just tested the output of those environment variables [here](https://github.com/alexhumphreys/idris2-node-postgres/runs/6720710535?check_suite_focus=true#step:4:1) so it should link to the correct run.

[ CI ] Add CI link automated commits

---

collections/HEAD.toml

This is the promise implementation which was used in `tyttp`.
It is now extracted as it seems to be stable enough to be in a separate library.

add idris2-promise, which was extracted from tyttp

---

.github/workflows/ci-db.yml
.github/workflows/ci-pr.yml
pack.toml

With this PR, we start using the latest docker image from pack, but we make sure to use the latest `pack-admin`. In addition, we now check the package collection on PRs.

[ CI ] simplify and add CI on PRs

---

.github/workflows/ci-pr.yml
.github/workflows/ci-test.yml
collections/HEAD.toml

I've finally modified the NCurses build to run C helper compilation through `ipkg` hooks so it should now be a reasonable addition to the Pack package set.

Add ncurses library to pack registry.

---

collections/HEAD.toml

Now `coop` fully switched to `pack` for everything

[ test ] Add test package to the existing `coop` package

---

collections/HEAD.toml

Does idris need another generic tree traversal library? probably not
did idris really need one to begin with? who knows
was it fun writing it? definitely

add multiplate

---

collections/HEAD.toml

I have informed package maintainers about this step. As soon as the packages build again, this can be undone.
Cf. octeep/idris2-http#4 and idris-bayes/monad-bayes#6 .

[ compat ] disable packages not building with current HEAD

---

collections/HEAD.toml

I'm temporarily disabling ncurses-idris until issue mattpolzin/ncurses-idris#34 has been fixed so that we can still get a new nightly.

[ temp ] temporarily disabling ncurses-idris

---

collections/HEAD.toml

Reverts stefan-hoeck/idris2-pack-db#110
The build issue due to a bug in totality should be resolved now on the main branch of `ncurses-idris`.

Revert "[ temp ] temporarily disabling ncurses-idris"

---

collections/HEAD.toml

This package only supports Chez/Racket for now, but it would be nice to have it support other backends. I pointed this out in it's `brief` field.

Add utf8 package

---

collections/HEAD.toml

Several PR's ago tests were added to `hedgehog`, but their status is not shown in the `STATUS.md`

[ hedgehog ] Enable existing tests in the db descriptor

---

collections/HEAD.toml

We are about to split `idris2-lsp` into `LSP-lib` (reusable model of LSP written in idris2) and `idris2-lsp` that will depend on `LSP-lib`. `LSP-lib` encourages authors to write LSP servers for other programming languages in Idris2. So it makes sense to change the name under which `idris2-lsp` is distributed via pack from generic `lsp` to more specific `idris2-lsp`.
EDIT: I guess CI will only pass when we merge the split.

Rename `lsp` to `idris2-lsp`

---

collections/HEAD.toml

Added packages, starting with the leaves of the dependency tree:
<dl>
<dt><tt>cont</tt>
<dd>Double-barreled continuations. Used in the <tt>pg</tt>, <tt>http2</tt>, <tt>web-server-racket</tt> packages.
<dt><tt>buf-conn</tt>
<dd>Buffered connection (as in TCP). Based on continuations. Let's you only read the amount of bytes you want.
<dt><tt>pg-types</tt>
<dd>Data types for PostgreSQL clients. Used in the <tt>pg</tt> and <tt>http2</tt> packages.
<dt><tt>http2</tt>
<dd>Continuation based HTTP2 server. No IO. Used in <tt>web-server-racket</tt>.
<dt><tt>pg</tt>
<dd>Continuation based PostgreSQL client. No IO use. Used in <tt>web-server-racket</tt>.
<dt><tt>racket-tcp</tt>
<dd>Thin bindings to the <tt>racket/tcp</tt> library. Supports concurrency using the Racket custodian. …

Add cont, buf-conn, http2, pg, pg-types, racket-tcp, web-server-racket, web-server-racket-hello-world

---

collections/HEAD.toml

This is a tiny package that provides string splitting functionality based on `memmem`. I needed this for a multi-part/MIME parser.

Add `string-search`

---

collections/HEAD.toml

Adding a bunch of small packages. This is all needed for SCRAM. SCRAM is needed to add more compatible authentication to my `pg` package.

Add base64, hash, hmac, scram, sha

---

collections/HEAD.toml

The service is currently unavailable and this is block pack switches and collection generation.

[ fix ] temporarily comment out packages from sourcehut

---

collections/nightly-240309.toml

I typically don't manually interfer with the generated nightlies, but `nightly-240309` is not usable, because idris2-lsp does not work due to upstream changes in the Idris compiler. So, we can either delete the nightly or adjust the idris2-lsp commit, since idris2-lsp has been fixed by now. I decided for the latter.

[ fix ] manually adjust Git commit for idris2-lsp in latest nightly

---

collections/HEAD.toml

Despite it is still under heavy construction, finally now we can add it, and it is meaningful, I think

[ new ] Add DepTyCheck library

---

collections/HEAD.toml

It is required for external projects which would like to use tyttp on node. Also required for tyttp-json tests.

[ new ] add tyttp adapter node

---

.github/workflows/ci-db.yml
.github/workflows/ci-pr.yml
.github/workflows/ci-test.yml
collections/HEAD.toml

- tyttp-json has been moved from its own github repository to tyttp repository
- tests were implemented for a while, but they were not enabled in pack-db before

[change] tyttp-json location and enable tests for tyttp packages

---

collections/HEAD.toml

Packages tls and http are currently broken. I informed the author but got no response so far. I'm therefore going to temporarily disable those two packages. Once they are fixed, we can enable them again.

[ admin ] temporarily disable tls and http

---

collections/HEAD.toml

If I understand correctly, this should allow katla-pandoc to be installed with `pack install-app katla-pandoc`, is that right?

Add Katla-pandoc

---

collections/HEAD.toml

I found this functionality to be usable elsewhere, so I think it deserves a separate library

[ split ] Pull `weaker-traversals` out of `summary-stat`

---

collections/HEAD.toml

This breaks not only the new pack collection build, but any type of work with `pack`, since now `pack` is designed to synchronise every package repository, even when it's actually unused.
Maybe @running-grass could come in an say whether this is a permanent deletion or not

[ remove ] Comment out suddenly disappeared packages
