collections/HEAD.toml

Still needs testing, but I think it's good enough to be published on pack-db

Add hashmap to HEAD.toml

---

collections/HEAD.toml

I tested these with a local pack.toml file and they built with
nightly-220527 so I think this should work, but I'm not sure how the
package set gets built so maybe I'm missing something.

Add tyttp and dependencies

---

collections/HEAD.toml

Cf. [stefan-hoeck/idris2-pack#80](https://github.com/stefan-hoeck/idris2-pack/pull/80).

[ fix ] LSP needs package path

---

collections/HEAD.toml

As discussed on [idris2-newtype-deriving#1](https://github.com/MarcelineVQ/idris2-newtype-deriving/issues/1).

[ HEAD ] added newtype-deriving

---

collections/HEAD.toml

this package is parser for markdown

add markdown package

---

collections/HEAD.toml

It's almost too little for a lib but I keep having to re-implement this in various projects, so after making it into a lib it made sense to put into the public in case others were doing the same.
I'm not sure how to run a CI for this so I hope I didn't make any errors

[ add ] TimeIt, dead simple HasIO action timing

---

.github/workflows/ci-db.yml

I'm giving up on making this more efficient for now. Some day, a person more knowledgeable in GitHub actions than me might come along.

[ CI ] restore again

---

collections/HEAD.toml

- if-unsolved-implicit
- typelevel-emptiness-collections
- random-pure

[ new ] Add some @buzden's libs

---

collections/HEAD.toml

This is a minimal benchmarking library

add park_bench

---

.github/workflows/ci-pr.yml
.github/workflows/ci-test.yml
collections/HEAD.toml

[ add ] adding idrisGL (https://github.com/ECburx/Idris2GL) to Pack

---

collections/HEAD.toml

Make idris2-go available through pack db.

add idris2-go

---

.github/workflows/ci-db.yml
.github/workflows/ci-pr.yml
.github/workflows/ci-test.yml
collections/HEAD.toml

Adding tests for idris2-go and idris2-go-lib.

add tests for idris2-go

---

collections/HEAD.toml

commit 6b8d3015a2317ab11e4a9205924d61094f570665 on monad-bayes should fix the main branch

Reinstate Monad-bayes

---

collections/HEAD.toml

Looks like this is the first non-Github repo, not sure whether there is any way I can point to the readme which is [here](https://git.sr.ht/~janus/lana/tree/master/item/Readme.md)

Add Lana (JSON schemas)

---

collections/HEAD.toml

I commented-out some packages that still fail to build. I'll try an come up with a new nightly with this fix, and hopefully we can then fix and reenable the failing packages.

[ compat ] temporarily disable failing packages

---

collections/nightly-240609.toml

I'll add this because we have it from a test run.

[ new ] manual nightly from test run

---

collections/HEAD.toml

A library I've been using for products, coproducts and sigma

add algdata

---

.github/workflows/ci-db.yml
.github/workflows/ci-pr.yml
.github/workflows/ci-test.yml
README.md
collections/HEAD.toml

Idris2 C binding to:
```
$ rpm -qf  /usr/include/rtl-sdr.h
rtl-sdr-devel-0.6.0^20230921git1261fbb2-3.fc40.x86_64
```
for folks to play with a cheap SDR in a dependently typed functional language.

[ new ] add rtlsdr

---

collections/HEAD.toml

Depends on idris-community/idris2-tls#11

[ wip ] [ change ] Enable idris2-http and idris2-tls.

---

collections/HEAD.toml

This package contains dependent variants of common types and interfaces, for example:
- `DShow, DEq, DOrd : (t -> Type) -> Type`
- `DList :  (f : a -> Type) -> (ts : List a) -> Type` - a list of dependent elements
and some other utils

Add my "dtypes" package

---

collections/HEAD.toml

This package currently only contains a priority queue implementation but I plan on adding several more data structures to it in the near future

Add my "structures" package

---

collections/HEAD.toml

- `theory` - a set of theorems; currently, mostly about lists
- `control-flow` - a model of a control flow graph, which enforces the correctness of its structure

Add my `theory` and `control-flow` packages

---

collections/HEAD.toml

Some basic support for decidable orderings in Idris.

Add new package decord

---

collections/HEAD.toml

This PR adds a new library, [idris2-systemd](https://github.com/Matthew-Mosior/idris2-systemd).
It also fixes spacing on many of the other packages in `collections/HEAD.toml`.

[ new ] add idris2-systemd

---

collections/HEAD.toml

Add byteorder package for converting fixed size numbers to and from collections of bytes

Add byteorder package

---

collections/HEAD.toml

Added the TensorType framework

Add TensorType
